### ISSUE TITLE
No output file

### ISSUE THREAD

**Issue by sir-shalahuddin** [andresinsitu/YOLO_slicing#1]
i want to ask something, i have try your code and i can't use it.

it says 

```
ejecutando main
100% 2/2 [00:00<00:00, 55188.21it/s]
```

without any error log

here is my cli 

```
python main.py --
folder_in test --folder_out test_slice --w 640 --h 640 --w_o 0.1 --h_o 0.1
```

**Comment by andressrodrl** [comment]
hi @sir-shalahuddin 
I´ve made it for my personal use, so it doesnt handle other cases or is developed properly to log errors etc. 

It only works with jpg images and the labels and images must be in the same folder. Is your folder_in like that?

Also it doesnt save images without labels. 

I might try to make a proper program if i have the time, thanks for your comment

**Comment by sir-shalahuddin** [comment]
<img width="152" alt="image" src="https://github.com/andresinsitu/YOLO_slicing/assets/64942988/e87ec638-7dc4-4c29-8dfd-a7f050156187">

i think i have follow the folder structure

**Comment by sir-shalahuddin** [comment]
oh i see, i place my images and labels in differet folder
